plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md
url: https://thingking-machine.github.io
baseurl: /gith

title: Thingking Machine
description: A machine is a thing. Things can not think. ...but some of them can thingk!

# Custom variables
github_settings:
  owner: thingking-machine
  repo: thingking_machine
  config_path: machina.yaml
  branch: main
  token_path: github.txt